volumes:
  cotacaoDB:

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: cotacaoDB

    ports:
      - "5432:5432"

    volumes:
      - cotacaoDB:/var/lib/postgresql/data